# parameters

ids:
    del12: /scicore/home/zavolan/zhu0006/3D_structure/IPA_candidates/snakemake_wf/aa_seq/del12.fasta
    del13: /scicore/home/zavolan/zhu0006/3D_structure/IPA_candidates/snakemake_wf/aa_seq/del13.fasta

params:
    N_AF: 5 # number of AlphaFold output models
    N_lowestTag: 3 # number of extracted pdb files after relax, with the lowest scores
    working_dir: /scicore/home/zavolan/zhu0006/3D_structure/IPA_candidates/snakemake_wf # current working directory
    relax_path: /scicore/home/zavolan/zhu0006/3D_structure/Rosetta/rosetta.binary.linux.release-371/main/source/bin/relax.static.linuxgccrelease # path to relax application
    extract_pdbs_path: /scicore/home/zavolan/zhu0006/3D_structure/Rosetta/rosetta.binary.linux.release-371/main/source/bin/extract_pdbs.static.linuxgccrelease # path to extract relax pdbs application
    per_residue_energies_path: /scicore/home/zavolan/zhu0006/3D_structure/Rosetta/rosetta_bin_linux_2021.16.61629_bundle/main/source/bin/per_residue_energies.static.linuxgccrelease # path to calculate per-residue energies for a structure
