ids:
  del12: /scicore/home/zavolan/zhu0006/3D_structure/IPA_candidates/snakemake_wf_betatest/aa_seq/del12.fasta
  del13: /scicore/home/zavolan/zhu0006/3D_structure/IPA_candidates/snakemake_wf_betatest/aa_seq/del13.fasta
params:
  N_AF: 5
  N_lowestTag: 3
  relax_nstruct: 5
  extract_pdbs_path: /scicore/home/zavolan/zhu0006/3D_structure/Rosetta/rosetta.binary.linux.release-371/main/source/bin/extract_pdbs.static.linuxgccrelease
  per_residue_energies_path: /scicore/home/zavolan/zhu0006/3D_structure/Rosetta/rosetta_bin_linux_2021.16.61629_bundle/main/source/bin/per_residue_energies.static.linuxgccrelease
  relax_path: /scicore/home/zavolan/zhu0006/3D_structure/Rosetta/rosetta.binary.linux.release-371/main/source/bin/relax.static.linuxgccrelease
  res_folder: test/alphafold_res
  working_dir: /scicore/home/zavolan/zhu0006/3D_structure/structural_stability_of_novel_orfs_hcc
  snakemake_wf_dir: /scicore/home/zavolan/zhu0006/3D_structure/structural_stability_of_novel_orfs_hcc/snakemake_wf_gpu
